apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: env
        operator: In
        values: [dev,test]
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: myapp
          image: nginx
