apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels: 
        env: test
spec:
    containers: 
      - name: nginxapp
        image: nginx      
        ports: 
           - containerPort: 80
