
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
spec:
  selector:
    matchLabels:
      app: nginx-daemon
  template:
    metadata:
      labels:
        app: nginx-daemon
    spec:
      nodeSelector:
        kubernetes.io/hostname: node   # run only on worker named "node"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
 